# vi: ft=ruby:ts=2:ai:sw=2
$script = <<-SCRIPT
echo "Provisioning OS"
sudo apt update
sudo apt install -y apache2
SCRIPT
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
        config.vm.provision "shell", inline: $script
        config.vm.synced_folder "web/", "/var/www/html"
        config.vm.network "forwarded_port", guest: 80, host: 8080
end